Add template, pattern and styles for Enterprise page
WordPress/wporg-main-2022 pull request #157
Opened 2022-12-14 22:43 UTC by adamwoodnz

Fixes #, See #.

Props <username>, <username>

### Screenshots

| Before | After |
|--------|-------|
| image  | image |

### How to test the changes in this Pull Request:

1.
2.
3.

2022-12-15 05:22 UTC, StevenDufresne commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<figure class="wp-block-image size-large"><img src="https://wordpress.org/files/2022/12/WordPress-Enterprise.png" alt="<?php _e( 'WordPress Enterprise', 'wporg' ); ?>" width="100%" height="100%"/></f
This `width` & `height` on the element is causing issues in the block editor I beleive.

 
<img width="300" alt="Screen Shot 2022-12-15 at 2 21 54 PM" src="https://user-images.githubusercontent.com/1657336/207779067-7832d26a-3d86-4e28-bcf4-cb618e0046a8.png">

2022-12-15 05:26 UTC, StevenDufresne commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<figure class="wp-block-image size-large is-resized"><img src="https://wordpress.org/files/2022/12/Enterprise-Use-Cases.png" alt="<?php _e( 'Enterprise Use Cases Image', 'wporg' ); ?>" width="402" he
This image is naturally cut off on the bottom. When the screen shrinks, before it is hidden, the cut off is visible.

`~1000px`
<img width="1141" alt="Screen Shot 2022-12-15 at 2 24 36 PM" src="https://user-images.githubusercontent.com/1657336/207779531-96ce1e52-947f-49fd-9390-eb8f50a08ce3.png">

2022-12-15 05:34 UTC, StevenDufresne commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<li><a href="https://wordpress.org/files/2020/11/IDC-Report-Choosing-a-CMS-to-Meet-Todays-Digital-Experience-Challenges.pdf" data-type="URL" data-id="https://wordpress.org/files/2020/11/IDC-Report-Ch
We need to be consistent with our "external" link icon. It appears like we have used that north-east arrow for external links here, but not on `https://wordpress.org/gutenberg/` or in the state of the word address banner currently on the homepage.

As per mat's request to have all external links on .org denoted, I implemented an external link class in https://github.com/WordPress/wporg-parent-2021/pull/53, assuming that's how we wanted to denote them (And how Gutenberg does). But if that's not the case, and we want to use `↗`,  let's figure that out so I can update: https://github.com/WordPress/wporg-parent-2021/pull/53. We currently are only using it on one link in the showcase.

@jasmussen @javierarce @beafialho

2022-12-15 05:43 UTC, StevenDufresne commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<h4 class="wp-block-heading"><?php _e( 'Extensibility', 'wporg' ); ?></h4>
Should these be level 2/3?

<img width="339" alt="Screen Shot 2022-12-15 at 2 40 29 PM" src="https://user-images.githubusercontent.com/1657336/207781657-5adc3e18-8ffe-4a59-a467-5e6aebafa24d.png">

2022-12-15 05:48 UTC, StevenDufresne commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<h2 class="wp-block-heading alignfull is-style-with-arrow has-inter-font-family has-heading-cta-font-size" style="font-style:normal;font-weight:300;letter-spacing:-2px"><a href="https://wordpress.org
This components stretches pretty wide. 

Not sure if that's what we want but in the showcase, this component stops at `1160px`

**Showcase**
<img width="1916" alt="Screen Shot 2022-12-15 at 2 47 28 PM" src="https://user-images.githubusercontent.com/1657336/207782528-9c70aa1d-40e0-43ad-ac4e-8f0eea27ae7d.png">
**This PR**
<img width="1916" alt="Screen Shot 2022-12-15 at 2 46 24 PM" src="https://user-images.githubusercontent.com/1657336/207782531-1df441f7-c9f2-473f-ac39-5a9742bb2871.png">

2022-12-15 05:50 UTC, StevenDufresne commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<h1 class="wp-block-heading screen-reader-text"><?php _e( 'WordPress Enterprise', 'wporg' ); ?></h1>
I just want to mention that this uses the same approach that showcase currently does which was flagged by a11y.


https://github.com/WordPress/wporg-showcase-2022/issues/89

2022-12-15 20:28 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<figure class="wp-block-image size-large"><img src="https://wordpress.org/files/2022/12/WordPress-Enterprise.png" alt="<?php _e( 'WordPress Enterprise', 'wporg' ); ?>" width="100%" height="100%"/></f
Ah I added that last minute to satisfy Lighthouse, will remove, thanks

2022-12-15 20:31 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<li><a href="https://wordpress.org/files/2020/11/IDC-Report-Choosing-a-CMS-to-Meet-Todays-Digital-Experience-Challenges.pdf" data-type="URL" data-id="https://wordpress.org/files/2020/11/IDC-Report-Ch
Happy to go with the preferred pattern here, seems like the class is?

2022-12-15 20:33 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<h2 class="wp-block-heading alignfull is-style-with-arrow has-inter-font-family has-heading-cta-font-size" style="font-style:normal;font-weight:300;letter-spacing:-2px"><a href="https://wordpress.org
Yeah it wasn't clear to me from the design; it appears like everything should stretch full width, but maybe it should be consistent with other sites rather than the sections above.

![Screen Shot 2022-12-16 at 9 32 20 AM](https://user-images.githubusercontent.com/1017872/207961098-140ca064-b142-4a2e-afd4-708542917fb4.jpg)

@jasmussen @javierarce @beafialho ?

2022-12-15 20:34 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<h1 class="wp-block-heading screen-reader-text"><?php _e( 'WordPress Enterprise', 'wporg' ); ?></h1>
I decided to be consistent until we have an approach using a webfont

2022-12-15 23:05 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<figure class="wp-block-image size-large is-resized"><img src="https://wordpress.org/files/2022/12/Enterprise-Use-Cases.png" alt="<?php _e( 'Enterprise Use Cases Image', 'wporg' ); ?>" width="402" he
This could be approached in 2 ways; the simple way is to position it at the bottom, always cut off and let it shrink down into the corner. The more complex way is to use the full image, positioned centrally with a slight translation lower and overflow hidden, and as it shrinks more of the image will come into view.

For now I've updated to the simple way.

2022-12-15 23:16 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<figure class="wp-block-image size-large"><img src="https://wordpress.org/files/2022/12/WordPress-Enterprise.png" alt="<?php _e( 'WordPress Enterprise', 'wporg' ); ?>" width="100%" height="100%"/></f
Removed

2022-12-15 23:23 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<h4 class="wp-block-heading"><?php _e( 'Extensibility', 'wporg' ); ?></h4>
Fixed

![Screen Shot 2022-12-16 at 12 23 07 PM](https://user-images.githubusercontent.com/1017872/207987689-543f1c01-2764-4230-931a-2e98602088be.jpg)

2022-12-15 23:55 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<h2 class="wp-block-heading alignfull is-style-with-arrow has-inter-font-family has-heading-cta-font-size" style="font-style:normal;font-weight:300;letter-spacing:-2px"><a href="https://wordpress.org
It would be really helpful actually if the designs showed a wider width so that we can tell if the layout is constrained or not. The current page design width is 1320px with the content at 1166px, which suggests to me that maybe all, or at least some of, these sections should be constrained, but I can't tell.

2022-12-16 00:25 UTC, StevenDufresne commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<li><a href="https://wordpress.org/files/2020/11/IDC-Report-Choosing-a-CMS-to-Meet-Todays-Digital-Experience-Challenges.pdf" data-type="URL" data-id="https://wordpress.org/files/2020/11/IDC-Report-Ch
I don't know. I'm still trying to lock down the experience:

https://github.com/WordPress/wporg-showcase-2022/pull/110#issuecomment-1353874722

The design team has the final say of course :)

2022-12-16 11:20 UTC, javierarce commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<li><a href="https://wordpress.org/files/2020/11/IDC-Report-Choosing-a-CMS-to-Meet-Todays-Digital-Experience-Challenges.pdf" data-type="URL" data-id="https://wordpress.org/files/2020/11/IDC-Report-Ch
We are reviewing some decisions about the use of the arrow icons to remove the discrepancies. 

We have updated the designs [here](https://www.figma.com/file/QK1zsWPQMTEYuar0SLepsI/Enterprise-Page?node-id=1%3A2193) to just use the classic icon for external links (and nothing on the internal ones).

![image](https://user-images.githubusercontent.com/4933/208086970-20d7f731-7163-4f66-b19b-f8ff45619a63.png)

cc: @panchovm

2022-12-16 11:52 UTC, panchovm commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<li><a href="https://wordpress.org/files/2020/11/IDC-Report-Choosing-a-CMS-to-Meet-Todays-Digital-Experience-Challenges.pdf" data-type="URL" data-id="https://wordpress.org/files/2020/11/IDC-Report-Ch
Based on what @javierarce shared above, we think the best approach is to use the [external link icon](https://github.com/WordPress/wporg-parent-2021/issues/64#issuecomment-1346174965) replacing the `↗︎` glyph in all external links.

On the other hand, it would be good to set all subdomain links as internal links and prevent showing the icon repeatedly in sections that don't need it, e.g. wp.org footer.

<img width="1305" alt="CleanShot 2022-12-16 at 12 50 41@2x" src="https://user-images.githubusercontent.com/895819/208092207-b710f64e-158b-4bf1-959e-08a0a9205070.png">

cc: @beafialho @StevenDufresne @bengreeley

2022-12-18 21:58 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<li><a href="https://wordpress.org/files/2020/11/IDC-Report-Choosing-a-CMS-to-Meet-Todays-Digital-Experience-Challenges.pdf" data-type="URL" data-id="https://wordpress.org/files/2020/11/IDC-Report-Ch
Replaced the characters with the SVG icon via the `external-link` class, note that the icon is `--wp--preset--color--charcoal-4` so we may need to do more work there

![Screen Shot 2022-12-19 at 10 54 26 AM](https://user-images.githubusercontent.com/1017872/208321570-c59c69cf-5ab1-4850-9f09-de956278f7e0.jpg)

2022-12-18 22:42 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<li><a href="https://wordpress.org/files/2020/11/IDC-Report-Choosing-a-CMS-to-Meet-Todays-Digital-Experience-Challenges.pdf" data-type="URL" data-id="https://wordpress.org/files/2020/11/IDC-Report-Ch
I see the color change is mentioned here https://github.com/WordPress/wporg-showcase-2022/pull/110#issuecomment-1354572161

2022-12-19 02:51 UTC, adamwoodnz commented
Updated screenshots below.

@javierarce @panchovm please let me know how you'd like the layout to behave at really wide sizes.

As you can see, currently at 1600px we're letting everything continue to stretch, but we could enforce the wide constrained width on some sections. The 'Use Cases' section will require custom CSS to position the left image correctly, as I haven't managed to find a way to use a constrained layout with the image remaining positioned to the bottom left in the editor using Cover or Media + Text.

| 1600px | 1320px (as designed) | Tablet | Mobile |
|--------|-------|-------|--------|
| ![localhost_8888_enterprise-2_](https://user-images.githubusercontent.com/1017872/208337670-244d9976-2986-43cc-a860-d49c68dda722.png)| ![localhost_8888_enterprise-2_ (1)](https://user-images.githubusercontent.com/1017872/208337659-3b4c25ff-0c5f-4f75-9823-c5fc6713958a.png) | ![localhost_8888_enterprise-2_(iPad)](https://user-images.githubusercontent.com/1017872/208337628-4937da3a-9466-430c-ac86-41681c479981.png) | ![localhost_8888_enterprise-2_(Samsung Galaxy S20 Ultra)](https://user-images.githubusercontent.com/1017872/208337614-4d921099-3696-427d-b188-9f5dc365a825.png) |

2022-12-20 09:02 UTC, fcoveram commented
I would follow the same approach as in the homepage. Setting a maximum width in the main grid, where text content is placed, and scaling up the image cropped by the section.

Fixing the image in the bottom left would add white space between the self and right side, breaking the three columns grid generated by being next to the Features section. Sharing a quick draft I made to see how it might work out.

<img width="400" alt="CleanShot 2022-12-20 at 09 51 09@2x" src="https://user-images.githubusercontent.com/895819/208623994-45179f71-a0d0-4030-b481-586cf9f6b74a.png">

|Fixed image|Scaled up image|
|:---|:---|
|<img width="1020" alt="CleanShot 2022-12-20 at 10 00 57@2x" src="https://user-images.githubusercontent.com/895819/208626431-b3d83d2e-2720-4667-bee2-2be65d309bf9.png">|<img width="1000" alt="CleanShot 2022-12-20 at 09 51 09@2x" src="https://user-images.githubusercontent.com/895819/208624421-345827f7-40e8-468f-aa0b-0136fe6a238e.png">|

---

On the other hand, I am noticing from the Mobile screenshot that "Try WordPress" section has a different letter-spacing value. I checked the same section in homepage by replacing the label, and the outcome looks less tight. I think we should follow that same style. Adding some screenshots

|Section in Mobile screenshot|Section in Homepage (`320px` viewport)|
|:---|:---|
<img width="300" alt="CleanShot 2022-12-20 at 09 55 23@2x" src="https://user-images.githubusercontent.com/895819/208625287-c2543bd2-a642-4675-a734-2dcb5d6c967b.png">|<img width="300" alt="CleanShot 2022-12-20 at 09 56 32@2x" src="https://user-images.githubusercontent.com/895819/208626008-3a8d5e14-8568-44a2-9170-59241ae9e82f.png">|

2023-01-04 23:07 UTC, adamwoodnz commented
> "Try WordPress" section has a different letter-spacing value

I had to reduce the letter spacing to `-6px` to make the text fit on one line on wide screens. At `-2px` it looks like this:

![Screen Shot 2023-01-05 at 12 04 00 PM](https://user-images.githubusercontent.com/1017872/210666656-b8acd5dc-3fb6-479e-874b-dc6e11226df1.jpg)

We could of course use different values on mobile and desktop, or reduce the font size. Let me know what you'd prefer @panchovm

2023-01-05 04:06 UTC, adamwoodnz commented
Updated screenshots below with constrained layout and 'Try WordPress' font size reduced to fit, rather than using letter spacing.

@javierarce @panchovm please let me know what you think.

| 1600px | 1320px (as designed) | Tablet | Mobile |
|--------|-------|-------|--------|
| ![localhost_8888_enterprise-2_ (3)](https://user-images.githubusercontent.com/1017872/210699537-6bf5c187-ba91-4c73-af0a-4079270b6573.png) | ![localhost_8888_enterprise-2_ (2)](https://user-images.githubusercontent.com/1017872/210699477-b9b36819-59ae-477c-bde5-300a6f972f91.png) | ![localhost_8888_enterprise-2_(iPad) (1)](https://user-images.githubusercontent.com/1017872/210699432-80c03967-5bf0-4e82-a411-19b08abf17a7.png) | ![localhost_8888_enterprise-2_(Samsung Galaxy S20 Ultra) (1)](https://user-images.githubusercontent.com/1017872/210699358-e1a58869-1b15-4e40-9878-7cdbcefeee40.png) |

2023-01-05 05:24 UTC, StevenDufresne commented
This looks good. 👍 

I do find that the "WordPress Enterprise" graphic gets blurry on my large desktop.

2023-01-05 21:25 UTC, adamwoodnz commented
> I do find that the "WordPress Enterprise" graphic gets blurry on my large desktop.

Yeah agreed, I'll bump it up a bit more.

2023-01-05 21:40 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/patterns/enterprise.php
> +<li><a href="https://wordpress.org/files/2020/11/IDC-Report-Choosing-a-CMS-to-Meet-Todays-Digital-Experience-Challenges.pdf" data-type="URL" data-id="https://wordpress.org/files/2020/11/IDC-Report-Ch
Color has been updated

2023-01-05 23:38 UTC, ryelle reviewed
Two pretty minor comments from a quick review, otherwise page looks good 👍🏻

2023-01-05 23:38 UTC, ryelle commented on source/wp-content/themes/wporg-main-2022/src/style/style.scss
> +	&-header .wp-block-columns {
We have a style rule about this, but I try to avoid using the `&` in selector names. I think it makes it harder to look at a single ruleset and know where it applies. Do you think it's useful here?

2023-01-05 23:38 UTC, ryelle commented on source/wp-content/themes/wporg-main-2022/src/style/style.scss
> +		gap: 0;
Can you use the block spacing setting for this? If you split it, you can use "vertical" to apply on mobile.

<img width="287" alt="Screenshot 2023-01-05 at 5 53 40 PM" src="https://user-images.githubusercontent.com/541093/210897766-481c43ff-352c-4fc0-bbd1-0b6b58a750a9.png">

2023-01-06 02:06 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/src/style/style.scss
> +	&-header .wp-block-columns {
Hmm I can see it might be problematic with a large number of nested selectors, where you've scrolled down far enough to lose sight of the prefix. In a small block like this, I like that it's DRY and it acts as a wrapper for the styles for this page. I guess we have comments for that though. Happy to refactor. Should it be failing lint? Could you please point me to the rule?

2023-01-06 02:08 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/src/style/style.scss
> +		gap: 0;
I would love to but I don't have the option to split, locally or in prod

![Screen Shot 2023-01-06 at 3 08 16 PM](https://user-images.githubusercontent.com/1017872/210915344-73217dd0-c9de-45ba-b00e-9bebd170d799.jpg)

2023-01-06 02:33 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/src/style/style.scss
> +		gap: 0;
Ignore, I was looking at a row block, not the columns. Updated.

2023-01-06 16:29 UTC, ryelle commented on source/wp-content/themes/wporg-main-2022/src/style/style.scss
> +	&-header .wp-block-columns {
Sorry, I mis-typed 🤦🏻  — we _don't_ have a style rule about this.

You're right that here it's a small enough section to not be a real problem, but I prefer to avoid this pattern always to remove the subjective "is this short enough" decision. I would appreciate a refactor.

I started an issue to discussing adding a rule to our project lint config https://github.com/WordPress/wporg-repo-tools/issues/25

2023-01-06 16:30 UTC, ryelle commented on source/wp-content/themes/wporg-main-2022/src/style/style.scss
> +		gap: 0;
I did the same thing when trying to take that screenshot 😁

2023-01-11 01:25 UTC, adamwoodnz commented on source/wp-content/themes/wporg-main-2022/src/style/style.scss
> +	&-header .wp-block-columns {
Code refactored and I commented on the issue.

2023-01-11 10:03 UTC, panchovm requested changes
I have been trying to set up and run the PR in my local, but I couldn't. So instead of keep pining folks for help and delaying my comments, I will share feedback based on the screenshots shared. Sorry for jumping in late.

The page looks great across breakpoints, I just noticed the following in mobile:
1. Images in Features section are slightly bigger compared to the mockup.
2. Top and bottom paddings look tighter compared to the mockup.
3. Section headings, below Try WordPress action, look smaller. The mockup's style is `Heading 5`.

The font-size reduction in Try WordPress works well.

2023-01-11 22:31 UTC, adamwoodnz commented
@panchovm thanks for the feedback!

> 3\. Section headings, below Try WordPress action, look smaller. The mockup's style is `Heading 5`

We have a rule in the parent theme for all the redesigned sites which reduces the size of H5 headings from 26px to 20px on mobile: https://github.com/WordPress/wporg-parent-2021/blob/trunk/source/wp-content/themes/wporg-parent-2021/theme.json#L334

Does this rule need to be adjusted? If it's not intended to be applied globally, we could specifically resize the other places it's applied, on the Download pages:

'Everything you need to set up your site just the way you want it.'
<img src="https://user-images.githubusercontent.com/1017872/211929825-1950e90d-4b98-44e2-9373-1370e2d96c76.jpg" height="300" />

'Number of WordPress 6.1 downloads'
<img src="https://user-images.githubusercontent.com/1017872/211929629-78a2add6-c3dd-4976-bab5-f7c50e55d93d.jpg" height="300" />

I have reduced the size of the Features image to match the design (now 58px high), and increased the padding on the header and features sections as they seemed the furthest off. Again these paddings are controlled globally and clamped on mobile so to some degree we try to go with settings that have been developed on other pages.

<img src="https://user-images.githubusercontent.com/1017872/211930501-0532f3ef-b50b-43f3-98d2-0dc9662c4765.png" width="412" />

2023-01-12 17:49 UTC, fcoveram approved these changes
The change looks great. We should keep consistency across the site, so your approach is perfect.

Thanks for the work ✨

2023-01-12 20:06 UTC, merged